### ISSUE TITLE
License..?

### ISSUE THREAD

**Issue by Omeryl** [UltimateHackers/Hash-Buster#3]
The README states there's a license, then what is it?

**Comment by tachyons** [comment]
Though the author says you can't copy code without his permission, he accepted GitHub terms and hence the code is open source

Ps : Not a legal advice

**Comment by Omeryl** [comment]
@tachyons I don't expect to use the code for anything, of course, but it's just a nasty habit to put stuff on the internet without a clear license ;).

**Comment by UltimateHackers** [comment]
License is clear. You can use the code but only after my permission.

**Comment by UltimateHackers** [comment]
But I will attach a proper license soon. Thanks.

**Comment by Omeryl** [comment]
So then what's the point of having it on GitHub? It's .. not open source if you have an irongrip.

**Comment by tachyons** [comment]
@UltimateHackers That is not a valid open source licence, So as long is this repo is public you can't enforce it

**Comment by althonos** [comment]
Using the GPL-3 means you give permission to anyone to use your code as long as they redistribute their modifications under the GPL license. If you don't want your code to be reused of redistributed anywhere, then you should use a proprietary custom license, for instance:

```
Copyright (C) 2017 UltimateHacker - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
```

**Comment by UltimateHackers** [comment]
Thanks @althonos but I don't want that either. I want people to use my programs to build something better but I also want to protect them from skids who just change the banner and tell people that they made this.

**Comment by UltimateHackers** [comment]
I have added GPL v3 license for now.

**Comment by Omeryl** [comment]
@UltimateHackers keep in mind that if anybody contributes under the GPL license, you cannot change it without their permission now.

**Comment by UltimateHackers** [comment]
Thanks everyone.
