### ISSUE TITLE
Add a configuration file to store alternate API tokens

### ISSUE THREAD

**Issue by rebrec** [UltimateHackers/Hash-Buster#8]
Might be interesting to not hardcode your API tokens since they might be rejected if your tool become popular (just a thought)

Anyway, nice tool !

**Comment by UltimateHackers** [comment]
Thanks for the concern.
Well just one service uses API token and before using that API, I requested its owner to remove the restrictions (like just 400 requests per day) and he agreed on that.
So as long as Hash Buster is open source, we are fine.
Regards.

**Comment by rebrec** [comment]
Great news thanks for the feedback
