### ISSUE TITLE
Add an other md5, sha1, sha224, sha256, sha384, sha512 hash database

### ISSUE THREAD

**Issue by webtobesocial** [UltimateHackers/Hash-Buster#9]
Great project so far, if you don't mind you could call the free and open API https://lea.kz/api. There you can query for a md5, sha1, sha224, sha256, sha384, sha512 hash or even for its clear text value.

**Comment by Viltaria** [comment]
#10

**Comment by Shad0wpf** [comment]
also can add https://somd5.com. This site can quer many complex password hash.

**Comment by UltimateHackers** [comment]
[Aded in v2.0]
Thanks a lot.
